version: '3.8'

services:
  app:
    image: tax-manager
    container_name: tax_manager_springboot_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: mariadb
    depends_on:
      - mariadb
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tax_manager
      MYSQL_USER: tax_app
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
